### ISSUE TITLE
test linear sync GH issue [APP-4]

### ISSUE THREAD

**Issue by ellie-narducci** [common-fate/granted-approvals#237]
initial description

**Comment by ellie-narducci** [comment]
Comment from [Linear (#4)](https://linear.app/common-fate/issue/APP-4/test-linear-sync-gh-issue-common-fategranted-approvals-237)

Linear comment

---
*via LinearSync*

**Comment by ellie-narducci** [comment]
GH comment

**Comment by chrnorm** [comment]
test comment

**Comment by ellie-narducci** [comment]
Comment from [Linear (#4)](https://linear.app/common-fate/issue/APP-4/test-linear-sync-gh-issue-common-fategranted-approvals-237)

test comment

---
*via LinearSync*

**Comment by chrnorm** [comment]
test comment

**Comment by ellie-narducci** [comment]
Comment from [Linear (#4)](https://linear.app/common-fate/issue/APP-4/test-linear-sync-gh-issue-common-fategranted-approvals-237)

test comment

---
*via LinearSync*
